# https://github.com/casey/just

# List justfile recipes
help:
    just --list

# Update the environment with the latest version of the dependencies
dev-sync:
    uv sync --all-extras --cache-dir .uv_cache

# Update the environment but not with the development dependencies
prod-sync:
    uv sync --all-extras --no-dev --cache-dir .uv_cache

# Fix the code style and format
fix: dev-sync
    uv run ruff check --fix
    uv run ruff format

# Execute the ruff code linter and format checker
check: dev-sync
    uv run ruff check

# Build the release package
build: dev-sync
    rm -rf dist
    uv build --wheel
    uv build --sdist

dev-run: dev-sync
    MAIL_PORT=1025 uv run scanapp

dev-run-smtpd: dev-sync
    uv run -m aiosmtpd -n -l localhost:1025

docker-build:
    docker build . --file srvapi.Dockerfile --tag ghcr.io/jdav-freiburg/scanner-srvapi:$(date +%Y-%m-%d)

docker-run:
    docker run --rm -ti -p 80 ghcr.io/jdav-freiburg/scanner-srvapi:$(date +%Y-%m-%d)